// Diagrams for the maths content.
//
// ─────────────────────────────────────────────────────────────────────────────
// WHY THIS EXISTS
//
// Matthew's note, after reading the maths topics properly: "when you explain
// the angle rules you should put the diagram of that rule." He is right, and
// it is the single biggest weakness in the maths content. "Alternate angles
// are equal — they form a Z shape" is not an explanation to somebody who does
// not already know the rule. It is a caption for a picture that was never
// drawn. Geometry is the one part of GCSE maths that cannot be taught in
// sentences, and every textbook and exam paper in the country agrees, because
// every one of them prints the diagram next to the rule.
//
// ─────────────────────────────────────────────────────────────────────────────
// HOW IT WORKS, AND WHY IT LOOKS LIKE Icon.tsx
//
// The content files stay PLAIN DATA. A key-fact block names the diagrams it
// wants — `diagrams: ["angles-on-a-line", "angles-around-a-point"]` — and this
// file turns a name into a drawing, exactly the way Icon.tsx turns "chip" into
// a chip and MASCOTS turns "hoot" into an owl. Content never imports a
// component, so nothing in app/lib/content/ has to know React exists.
//
// A name that does not exist here renders nothing at all, silently — which is
// the failure shape this codebase keeps getting caught by. So there is a check
// in scripts/check-content.mjs that fails the build if a content file names a
// diagram this file does not export.
//
// ─────────────────────────────────────────────────────────────────────────────
// THE ARCS ARE COMPUTED, NOT HAND-WRITTEN
//
// An SVG arc is `A rx ry rotation large-arc-flag sweep-flag x y`, and getting
// the two flags wrong silently draws the arc the long way round the circle —
// which on an angle diagram means labelling 135° as 225°. A wrong maths
// diagram is worse than no diagram, so the arcs come from `arc()` and
// `wedge()` below, which take plain degrees measured the way a maths student
// measures them: anticlockwise from the positive x-axis.
//
// The regular polygon is generated by a loop for the same reason — five
// exterior angles worked out by hand is five chances to be wrong.
// ─────────────────────────────────────────────────────────────────────────────

// SVG puts y DOWNWARDS, maths puts it upwards. Every angle in this file is a
// normal maths angle and this one function is the only place that difference
// is dealt with.
function polar(cx: number, cy: number, r: number, degrees: number) {
  const radians = (degrees * Math.PI) / 180;
  return [cx + r * Math.cos(radians), cy - r * Math.sin(radians)] as const;
}

/** An arc of a circle, from one angle to another, anticlockwise. */
function arc(cx: number, cy: number, r: number, from: number, to: number) {
  const [x1, y1] = polar(cx, cy, r, from);
  const [x2, y2] = polar(cx, cy, r, to);
  const largeArc = Math.abs(to - from) > 180 ? 1 : 0;
  // Increasing maths angle is anticlockwise, and because y is flipped that is
  // sweep-flag 0 in SVG. Going backwards through the angles is sweep-flag 1.
  const sweep = to > from ? 0 : 1;
  return `M ${x1.toFixed(2)} ${y1.toFixed(2)} A ${r} ${r} 0 ${largeArc} ${sweep} ${x2.toFixed(2)} ${y2.toFixed(2)}`;
}

/** The filled slice of pie between two angles — the shaded bit of an angle. */
function wedge(cx: number, cy: number, r: number, from: number, to: number) {
  return `${arc(cx, cy, r, from, to)} L ${cx} ${cy} Z`;
}

/** A short line from one point in a given direction — for extending a side. */
function ray(cx: number, cy: number, r: number, degrees: number) {
  const [x, y] = polar(cx, cy, r, degrees);
  return `M ${cx} ${cy} L ${x.toFixed(2)} ${y.toFixed(2)}`;
}

// ─── Shared styling ─────────────────────────────────────────────────────────
//
// Two colours only. The FIGURE is `currentColor`, so it takes the page's own
// text colour and is therefore correct in dark mode without a single extra
// rule. The ANGLES are the site's blue, which is the one thing that should
// stand out from the lines it sits between.
//
// Equal angles are marked with matching numbers of arcs, not with different
// colours — that is what a real textbook does, and it is the version that
// still works for a colour-blind student.
const line = "stroke-current opacity-60";
const angleStroke = "stroke-blue-600 dark:stroke-blue-400";
const angleFill = "fill-blue-600/10 dark:fill-blue-400/20";
const label = "fill-blue-700 dark:fill-blue-300 text-[13px] font-semibold";
const plainLabel = "fill-current text-[11px] opacity-70";

function Angle({ d }: { d: string }) {
  return <path d={d} className={`${angleFill} ${angleStroke}`} strokeWidth={1.6} />;
}

function Mark({ d }: { d: string }) {
  return <path d={d} className={angleStroke} strokeWidth={1.6} fill="none" />;
}

function Fig({ d, dashed = false }: { d: string; dashed?: boolean }) {
  return (
    <path
      d={d}
      className={line}
      strokeWidth={2}
      fill="none"
      strokeLinecap="round"
      strokeDasharray={dashed ? "5 4" : undefined}
    />
  );
}

// A small square in the corner, the standard way of saying "this is 90°".
function RightAngle({ x, y, dx, dy }: { x: number; y: number; dx: number; dy: number }) {
  const s = 9;
  return (
    <path
      d={`M ${x + dx * s} ${y} L ${x + dx * s} ${y + dy * s} L ${x} ${y + dy * s}`}
      className={angleStroke}
      strokeWidth={1.6}
      fill="none"
    />
  );
}

type DiagramProps = { className?: string };

// ════════════════════════════════════════════════════════════════════════════
// THE DIAGRAMS
// ════════════════════════════════════════════════════════════════════════════

function Frame({
  label: ariaLabel,
  caption: captionText,
  children,
  className,
}: {
  label: string;
  caption?: string;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <figure className={className}>
      <svg
        viewBox="0 0 220 112"
        role="img"
        aria-label={ariaLabel}
        className="h-auto w-full"
      >
        {children}
      </svg>

      {/* The caption used to be an SVG <text> inside the picture, and on over
          half the diagrams it was CLIPPED — the viewBox is 220 units wide, so
          anything longer than about forty characters ran off both ends and
          "the exterior angle = the two opposite interior angles" rendered as
          "terior angle = the two opposite interior a".

          Found by rendering all 28 and looking at them, which is the only way
          this kind of thing ever gets found. As real HTML it wraps instead of
          clipping, scales with the reader's font size rather than with the
          width of the column, and can be selected and read aloud. */}
      {captionText ? (
        <figcaption className="mt-1.5 text-center text-sm leading-snug opacity-70">
          {captionText}
        </figcaption>
      ) : null}
    </figure>
  );
}

// ─── Basic angle facts ──────────────────────────────────────────────────────

function AnglesOnALine(props: DiagramProps) {
  return (
    <Frame
      caption={"a + b = 180°"}
      {...props}
      label="A straight line with a ray from a point on it, splitting the 180 degrees into two angles a and b"
    >
      <Fig d="M 20 80 L 200 80" />
      <Fig d={ray(100, 80, 72, 45)} />
      <Angle d={wedge(100, 80, 34, 45, 180)} />
      <Angle d={wedge(100, 80, 23, 0, 45)} />
      <circle cx={100} cy={80} r={2.6} className="fill-current opacity-60" />
      <text x={74} y={62} className={label}>a</text>
      <text x={130} y={73} className={label}>b</text>
    </Frame>
  );
}

function AnglesAroundAPoint(props: DiagramProps) {
  const cx = 110;
  const cy = 58;
  const rays = [70, 155, 235, 320];
  const radii = [30, 20, 30, 20];
  const names = ["a", "b", "c", "d"];
  return (
    <Frame
      caption={"a + b + c + d = 360°"}
      {...props}
      label="Four rays from a single point, dividing the full turn into four angles a, b, c and d"
    >
      {rays.map((deg) => (
        <Fig key={deg} d={ray(cx, cy, 62, deg)} />
      ))}
      {rays.map((deg, i) => {
        const next = i === rays.length - 1 ? rays[0] + 360 : rays[i + 1];
        const mid = (deg + next) / 2;
        const [lx, ly] = polar(cx, cy, radii[i] + 12, mid);
        return (
          <g key={`a${deg}`}>
            {/* Outlined arcs, not filled wedges. Four filled wedges tile
                the whole turn, so their union is a solid disc and you cannot
                see where one angle stops and the next starts — which is the
                one thing this diagram exists to show. Found by rendering it. */}
            <Mark d={arc(cx, cy, radii[i], deg, next)} />
            <text x={lx} y={ly + 4} textAnchor="middle" className={label}>
              {names[i]}
            </text>
          </g>
        );
      })}
      <circle cx={cx} cy={cy} r={2.6} className="fill-current opacity-60" />
    </Frame>
  );
}

function VerticallyOpposite(props: DiagramProps) {
  const cx = 110;
  const cy = 55;
  return (
    <Frame
      caption={"opposite angles are equal"}
      {...props}
      label="Two straight lines crossing, showing that the two pairs of opposite angles are equal"
    >
      <Fig d={`${ray(cx, cy, 88, 25)} ${ray(cx, cy, 88, 205)}`} />
      <Fig d={`${ray(cx, cy, 88, 145)} ${ray(cx, cy, 88, 325)}`} />
      {/* One arc each: the top and bottom angles are the equal pair. */}
      <Angle d={wedge(cx, cy, 14, 25, 145)} />
      <Angle d={wedge(cx, cy, 14, 205, 325)} />
      {/* Two arcs each: the left and right pair, equal to each other but not
          to the first pair. Matching arc COUNTS is how a textbook says "these
          two are equal", and unlike colour it still works in black and white
          on the printable sheet. */}
      <Mark d={arc(cx, cy, 20, 325, 385)} />
      <Mark d={arc(cx, cy, 25, 325, 385)} />
      <Mark d={arc(cx, cy, 20, 145, 205)} />
      <Mark d={arc(cx, cy, 25, 145, 205)} />
      <text x={106} y={18} className={label}>a</text>
      <text x={106} y={100} className={label}>a</text>
      <text x={168} y={62} className={label}>b</text>
      <text x={44} y={62} className={label}>b</text>
    </Frame>
  );
}

function AnglesInATriangle(props: DiagramProps) {
  return (
    <Frame
      caption={"a + b + c = 180°"}
      {...props}
      label="A triangle with its three interior angles a, b and c marked"
    >
      <Fig d="M 30 92 L 190 92 L 120 26 Z" />
      <Angle d={wedge(30, 92, 26, 0, 37.9)} />
      <Angle d={wedge(190, 92, 26, 135, 180)} />
      <Angle d={wedge(120, 26, 22, 217.9, 315)} />
      <text x={57} y={86} className={label}>a</text>
      <text x={165} y={86} className={label}>b</text>
      <text x={115} y={54} className={label}>c</text>
    </Frame>
  );
}

// ─── Parallel lines ─────────────────────────────────────────────────────────
//
// All three share one figure: two parallel lines and a transversal cutting
// them. Only the shaded pair changes, which is the whole point — students mix
// these up precisely because the picture is the same every time and only the
// position of the pair differs.

const PARALLEL_TOP = 32;
const PARALLEL_BOTTOM = 86;
const CUT_LOWER = { x: 76.1, y: PARALLEL_BOTTOM };
const CUT_UPPER = { x: 128.9, y: PARALLEL_TOP };
const CUT_ANGLE = 43.5;

function ParallelFrame({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Fig d={`M 16 ${PARALLEL_TOP} L 204 ${PARALLEL_TOP}`} />
      <Fig d={`M 16 ${PARALLEL_BOTTOM} L 204 ${PARALLEL_BOTTOM}`} />
      <Fig d="M 55 105 L 150 15" />
      {/* The little arrowheads that mean "these lines are parallel". Students
          are expected to read them in the exam, so they belong here. */}
      <Mark d="M 34 27 L 41 32 L 34 37" />
      <Mark d={`M 34 ${PARALLEL_BOTTOM - 5} L 41 ${PARALLEL_BOTTOM} L 34 ${PARALLEL_BOTTOM + 5}`} />
      {children}
    </>
  );
}

function ParallelCorresponding(props: DiagramProps) {
  return (
    <Frame
      caption={"corresponding — equal (F shape)"}
      {...props}
      label="Two parallel lines cut by a transversal, with the two equal corresponding angles shaded in the same position at each crossing, forming an F shape"
    >
      <ParallelFrame>
        <Angle d={wedge(CUT_LOWER.x, CUT_LOWER.y, 24, 0, CUT_ANGLE)} />
        <Angle d={wedge(CUT_UPPER.x, CUT_UPPER.y, 24, 0, CUT_ANGLE)} />
        <text x={104} y={82} className={label}>a</text>
        <text x={157} y={28} className={label}>a</text>
      </ParallelFrame>
    </Frame>
  );
}

function ParallelAlternate(props: DiagramProps) {
  return (
    <Frame
      caption={"alternate — equal (Z shape)"}
      {...props}
      label="Two parallel lines cut by a transversal, with the two equal alternate angles shaded on opposite sides of the transversal between the lines, forming a Z shape"
    >
      <ParallelFrame>
        <Angle d={wedge(CUT_LOWER.x, CUT_LOWER.y, 26, CUT_ANGLE, 180)} />
        <Angle d={wedge(CUT_UPPER.x, CUT_UPPER.y, 26, 223.5, 360)} />
        <text x={52} y={76} className={label}>a</text>
        <text x={152} y={48} className={label}>a</text>
      </ParallelFrame>
    </Frame>
  );
}

function ParallelCoInterior(props: DiagramProps) {
  return (
    <Frame
      caption={"co-interior — a + b = 180° (C shape)"}
      {...props}
      label="Two parallel lines cut by a transversal, with the two co-interior angles shaded on the same side of the transversal between the lines, forming a C shape"
    >
      <ParallelFrame>
        <Angle d={wedge(CUT_LOWER.x, CUT_LOWER.y, 26, CUT_ANGLE, 180)} />
        <Angle d={wedge(CUT_UPPER.x, CUT_UPPER.y, 26, 180, 223.5)} />
        <text x={52} y={76} className={label}>a</text>
        <text x={104} y={44} className={label}>b</text>
      </ParallelFrame>
    </Frame>
  );
}

// ─── Triangles and polygons ─────────────────────────────────────────────────

function ExteriorAngleTriangle(props: DiagramProps) {
  return (
    <Frame
      caption={"the exterior angle = the two opposite interior angles"}
      {...props}
      label="A triangle with one side extended, showing that the exterior angle equals the sum of the two opposite interior angles"
    >
      <Fig d="M 35 88 L 150 88 L 95 28 Z" />
      <Fig d="M 150 88 L 205 88" dashed />
      <Angle d={wedge(35, 88, 24, 0, 45)} />
      <Angle d={wedge(95, 28, 20, 225, 312.5)} />
      <Angle d={wedge(150, 88, 30, 0, 132.5)} />
      <text x={60} y={83} className={label}>a</text>
      <text x={90} y={58} className={label}>b</text>
      <text x={160} y={70} className={label}>a + b</text>
    </Frame>
  );
}

function PolygonExteriorAngles(props: DiagramProps) {
  // Generated rather than hand-drawn. Five exterior angles worked out by hand
  // is five chances to put an arc in the wrong place — and the loop also makes
  // the point the diagram is teaching: it does not matter how many sides there
  // are, because every extra side adds a turn and the total stays 360°.
  const cx = 110;
  const cy = 56;
  const r = 40;
  const n = 5;
  const points = Array.from({ length: n }, (_, i) => polar(cx, cy, r, 90 + (360 / n) * i));

  return (
    <Frame
      caption={"the exterior angles always add to 360°"}
      {...props}
      label="A regular pentagon with each side extended and the five exterior angles shaded, which together make one full turn"
    >
      <Fig d={`M ${points.map(([x, y]) => `${x.toFixed(1)} ${y.toFixed(1)}`).join(" L ")} Z`} />
      {points.map(([x, y], i) => {
        const [px] = points[(i + n - 1) % n];
        const [, py] = points[(i + n - 1) % n];
        const [nx, ny] = points[(i + 1) % n];
        // Direction the previous side was travelling, continued past this
        // corner — that extension is one arm of the exterior angle.
        const incoming = (Math.atan2(-(y - py), x - px) * 180) / Math.PI;
        const outgoing = (Math.atan2(-(ny - y), nx - x) * 180) / Math.PI;
        // The exterior angle is the TURN from one side to the next, and a turn
        // is only ever the short way round. atan2 returns values in (-180, 180],
        // so at one corner of the pentagon incoming and outgoing land on
        // opposite sides of that wrap and their raw difference came out as
        // -288° instead of +72° — arc() dutifully drew the 288° reflex angle,
        // which is exactly what the diagram was showing before this line.
        let turn = outgoing - incoming;
        while (turn > 180) turn -= 360;
        while (turn <= -180) turn += 360;
        return (
          <g key={i}>
            <Fig d={ray(x, y, 22, incoming)} dashed />
            <Angle d={wedge(x, y, 15, incoming, incoming + turn)} />
          </g>
        );
      })}
    </Frame>
  );
}

// ─── Area ───────────────────────────────────────────────────────────────────

function TrianglePerpendicularHeight(props: DiagramProps) {
  return (
    <Frame
      caption={"area = ½ × base × perpendicular height"}
      {...props}
      label="A triangle with the perpendicular height drawn as a dashed line from the apex down to the base, meeting it at a right angle, next to the slanted side which is not the height"
    >
      <Fig d="M 30 92 L 185 92 L 120 30 Z" />
      <Fig d="M 120 30 L 120 92" dashed />
      <RightAngle x={120} y={92} dx={1} dy={-1} />
      <text x={98} y={64} textAnchor="end" className={label}>h</text>
      <text x={100} y={108} textAnchor="middle" className={plainLabel}>base</text>
      <text x={162} y={56} className={plainLabel}>not h</text>
    </Frame>
  );
}

function TrapeziumArea(props: DiagramProps) {
  return (
    <Frame
      caption={"area = ½ × (a + b) × h"}
      {...props}
      label="A trapezium with its two parallel sides labelled a and b and the perpendicular height h drawn as a dashed line between them"
    >
      <Fig d="M 30 90 L 190 90 L 155 32 L 68 32 Z" />
      <Fig d="M 100 32 L 100 90" dashed />
      <RightAngle x={100} y={90} dx={1} dy={-1} />
      <Mark d="M 68 26 L 155 26" />
      <Mark d="M 30 96 L 190 96" />
      <text x={111} y={22} textAnchor="middle" className={label}>a</text>
      <text x={110} y={108} textAnchor="middle" className={label}>b</text>
      <text x={92} y={64} textAnchor="end" className={label}>h</text>
    </Frame>
  );
}


// ─── Circles ────────────────────────────────────────────────────────────────
//
// Circle theorems are the clearest case in the whole subject for this file
// existing. "The angle at the centre is twice the angle at the circumference"
// is not a sentence anybody has ever learned from. It is a caption.
//
// Every circle below uses the same centre and radius, so the theorems can be
// compared against each other — the exam skill is spotting WHICH one applies,
// and that is much harder when every picture is a different size.

const CIRCLE = { cx: 110, cy: 56, r: 40 };

function onCircle(degrees: number) {
  return polar(CIRCLE.cx, CIRCLE.cy, CIRCLE.r, degrees);
}

function CircleFrame({ children }: { children: React.ReactNode }) {
  return (
    <>
      <circle
        cx={CIRCLE.cx}
        cy={CIRCLE.cy}
        r={CIRCLE.r}
        className={line}
        strokeWidth={2}
        fill="none"
      />
      {children}
    </>
  );
}

function chord(a: number, b: number) {
  const [x1, y1] = onCircle(a);
  const [x2, y2] = onCircle(b);
  return `M ${x1.toFixed(1)} ${y1.toFixed(1)} L ${x2.toFixed(1)} ${y2.toFixed(1)}`;
}

/** The angle, in maths degrees, from the point at `from` to the point at `to`. */
function bearingBetween(from: number, to: number) {
  const [x1, y1] = onCircle(from);
  const [x2, y2] = onCircle(to);
  return (Math.atan2(-(y2 - y1), x2 - x1) * 180) / Math.PI;
}

function CircleParts(props: DiagramProps) {
  return (
    <Frame
      caption={"a tangent touches at exactly one point"} {...props} label="A circle labelled with its radius, diameter, chord and tangent">
      <CircleFrame>
        <Fig d={`M ${CIRCLE.cx} ${CIRCLE.cy} L ${onCircle(125)[0].toFixed(1)} ${onCircle(125)[1].toFixed(1)}`} />
        <Fig d={chord(0, 180)} />
        <Fig d={chord(300, 240)} />
        <Fig d="M 150 96 L 190 16" />
        <circle cx={CIRCLE.cx} cy={CIRCLE.cy} r={2.6} className="fill-current opacity-60" />
        {/* Every one of these sat ON the line it was naming until the
            diagrams were rendered and looked at. They are now pushed clear:
            radius above its own line, diameter below the horizontal, chord
            outside the circle with a leader of white space. */}
        <text x={62} y={26} textAnchor="middle" className={plainLabel}>radius</text>
        <text x={104} y={74} className={plainLabel}>diameter</text>
        <text x={96} y={108} textAnchor="middle" className={plainLabel}>chord</text>
        <text x={172} y={40} className={plainLabel}>tangent</text>
      </CircleFrame>
    </Frame>
  );
}

function CircleAngleAtCentre(props: DiagramProps) {
  const A = 210;
  const B = 330;
  const P = 90;
  const [ax, ay] = onCircle(A);
  const [bx, by] = onCircle(B);
  const [px, py] = onCircle(P);
  return (
    <Frame
      caption={"angle at the centre = twice the angle at the edge"}
      {...props}
      label="A circle where the angle subtended at the centre by a chord is twice the angle subtended at the circumference by the same chord"
    >
      <CircleFrame>
        <Fig d={`M ${ax.toFixed(1)} ${ay.toFixed(1)} L ${CIRCLE.cx} ${CIRCLE.cy} L ${bx.toFixed(1)} ${by.toFixed(1)}`} />
        <Fig d={`M ${ax.toFixed(1)} ${ay.toFixed(1)} L ${px.toFixed(1)} ${py.toFixed(1)} L ${bx.toFixed(1)} ${by.toFixed(1)}`} />
        <Angle d={wedge(CIRCLE.cx, CIRCLE.cy, 18, A, B - 360)} />
        <Angle d={wedge(px, py, 22, bearingBetween(P, A), bearingBetween(P, B))} />
        <text x={110} y={88} textAnchor="middle" className={label}>2x</text>
        <text x={110} y={45} textAnchor="middle" className={label}>x</text>
      </CircleFrame>
    </Frame>
  );
}

function CircleSemicircle(props: DiagramProps) {
  const [ax, ay] = onCircle(180);
  const [bx, by] = onCircle(0);
  const [px, py] = onCircle(70);
  return (
    <Frame
      caption={"the angle in a semicircle is 90°"}
      {...props}
      label="A triangle drawn on a diameter of a circle, with the angle at the circumference marked as a right angle"
    >
      <CircleFrame>
        <Fig d={chord(180, 0)} />
        <Fig d={`M ${ax.toFixed(1)} ${ay.toFixed(1)} L ${px.toFixed(1)} ${py.toFixed(1)} L ${bx.toFixed(1)} ${by.toFixed(1)}`} />
        <Angle d={wedge(px, py, 13, bearingBetween(70, 0), bearingBetween(70, 180))} />
        <circle cx={CIRCLE.cx} cy={CIRCLE.cy} r={2.6} className="fill-current opacity-60" />
        <text x={116} y={48} textAnchor="middle" className={label}>90°</text>
      </CircleFrame>
    </Frame>
  );
}

function CircleSameSegment(props: DiagramProps) {
  const A = 200;
  const B = 340;
  return (
    <Frame
      caption={"angles in the same segment are equal"}
      {...props}
      label="Two angles standing on the same chord from different points on the same arc, marked as equal"
    >
      <CircleFrame>
        <Fig d={chord(A, B)} />
        {[60, 115].map((P) => {
          const [ax, ay] = onCircle(A);
          const [bx, by] = onCircle(B);
          const [px, py] = onCircle(P);
          return (
            <g key={P}>
              <Fig d={`M ${ax.toFixed(1)} ${ay.toFixed(1)} L ${px.toFixed(1)} ${py.toFixed(1)} L ${bx.toFixed(1)} ${by.toFixed(1)}`} />
              <Angle d={wedge(px, py, 15, bearingBetween(P, B), bearingBetween(P, A))} />
            </g>
          );
        })}
        <text x={124} y={40} className={label}>x</text>
        <text x={80} y={44} className={label}>x</text>
      </CircleFrame>
    </Frame>
  );
}

function CircleCyclicQuadrilateral(props: DiagramProps) {
  const pts = [55, 145, 215, 325];
  const [p0, p1, p2, p3] = pts.map((d) => onCircle(d));
  return (
    <Frame
      caption={"opposite angles: a + b = 180°"}
      {...props}
      label="A quadrilateral with all four corners on a circle, with one pair of opposite angles marked as adding to 180 degrees"
    >
      <CircleFrame>
        <Fig
          d={`M ${p0[0].toFixed(1)} ${p0[1].toFixed(1)} L ${p1[0].toFixed(1)} ${p1[1].toFixed(1)} L ${p2[0].toFixed(1)} ${p2[1].toFixed(1)} L ${p3[0].toFixed(1)} ${p3[1].toFixed(1)} Z`}
        />
        <Angle d={wedge(p0[0], p0[1], 15, bearingBetween(55, 145), bearingBetween(55, 325) + 360)} />
        <Angle d={wedge(p2[0], p2[1], 15, bearingBetween(215, 325), bearingBetween(215, 145))} />
        <text x={144} y={44} className={label}>a</text>
        <text x={68} y={82} className={label}>b</text>
      </CircleFrame>
    </Frame>
  );
}

function CircleTangentRadius(props: DiagramProps) {
  const [tx, ty] = onCircle(0);
  return (
    <Frame
      caption={"a tangent meets a radius at 90°"}
      {...props}
      label="A tangent meeting a circle, with the radius drawn to the point of contact and a right angle marked between them"
    >
      <CircleFrame>
        <Fig d={`M ${CIRCLE.cx} ${CIRCLE.cy} L ${tx.toFixed(1)} ${ty.toFixed(1)}`} />
        <Fig d={`M ${tx.toFixed(1)} 14 L ${tx.toFixed(1)} 98`} />
        <RightAngle x={tx} y={ty} dx={-1} dy={-1} />
        <circle cx={CIRCLE.cx} cy={CIRCLE.cy} r={2.6} className="fill-current opacity-60" />
        <text x={96} y={72} className={plainLabel}>radius</text>
        <text x={156} y={24} className={plainLabel}>tangent</text>
      </CircleFrame>
    </Frame>
  );
}

function CircleAlternateSegment(props: DiagramProps) {
  const T = 270;
  const A = 20;
  const B = 160;
  const [tx, ty] = onCircle(T);
  const [ax, ay] = onCircle(A);
  const [bx, by] = onCircle(B);
  return (
    <Frame
      caption={"tangent–chord = the angle in the alternate segment"}
      {...props}
      label="The angle between a tangent and a chord, marked equal to the angle in the alternate segment"
    >
      <CircleFrame>
        <Fig d={`M 46 ${ty.toFixed(1)} L 174 ${ty.toFixed(1)}`} />
        <Fig d={`M ${tx.toFixed(1)} ${ty.toFixed(1)} L ${ax.toFixed(1)} ${ay.toFixed(1)}`} />
        <Fig d={`M ${bx.toFixed(1)} ${by.toFixed(1)} L ${ax.toFixed(1)} ${ay.toFixed(1)}`} />
        <Fig d={`M ${bx.toFixed(1)} ${by.toFixed(1)} L ${tx.toFixed(1)} ${ty.toFixed(1)}`} />
        <Angle d={wedge(tx, ty, 20, 0, bearingBetween(T, A))} />
        <Angle d={wedge(bx, by, 16, bearingBetween(B, T), bearingBetween(B, A))} />
        <text x={132} y={90} className={label}>x</text>
        <text x={78} y={54} className={label}>x</text>
      </CircleFrame>
    </Frame>
  );
}

function CircleSectorArc(props: DiagramProps) {
  return (
    <Frame
      caption={"arc = (θ ÷ 360) × circumference"}
      {...props}
      label="A shaded sector of a circle with the angle at the centre marked and the arc highlighted"
    >
      <CircleFrame>
        <path
          d={wedge(CIRCLE.cx, CIRCLE.cy, CIRCLE.r, 25, 115)}
          className={angleFill}
          stroke="none"
        />
        <Fig d={`M ${CIRCLE.cx} ${CIRCLE.cy} L ${onCircle(25)[0].toFixed(1)} ${onCircle(25)[1].toFixed(1)}`} />
        <Fig d={`M ${CIRCLE.cx} ${CIRCLE.cy} L ${onCircle(115)[0].toFixed(1)} ${onCircle(115)[1].toFixed(1)}`} />
        <path
          d={arc(CIRCLE.cx, CIRCLE.cy, CIRCLE.r, 25, 115)}
          className={angleStroke}
          strokeWidth={3}
          fill="none"
        />
        <Mark d={arc(CIRCLE.cx, CIRCLE.cy, 15, 25, 115)} />
        <text x={124} y={48} className={label}>θ</text>
        <text x={150} y={22} className={plainLabel}>arc</text>
      </CircleFrame>
    </Frame>
  );
}

// ─── Pythagoras and trigonometry ────────────────────────────────────────────

function Pythagoras(props: DiagramProps) {
  return (
    <Frame
      caption={"a² + b² = c² — c is always the longest side"}
      {...props}
      label="A right-angled triangle with the two shorter sides labelled a and b and the hypotenuse labelled c"
    >
      <Fig d="M 45 92 L 165 92 L 45 26 Z" />
      <RightAngle x={45} y={92} dx={1} dy={-1} />
      <text x={105} y={107} textAnchor="middle" className={label}>b</text>
      <text x={34} y={62} textAnchor="end" className={label}>a</text>
      <text x={112} y={52} className={label}>c</text>
    </Frame>
  );
}

function Sohcahtoa(props: DiagramProps) {
  return (
    <Frame
      caption={"opposite and adjacent are named from θ, not from the page"}
      {...props}
      label="A right-angled triangle with an angle marked, and the sides labelled opposite, adjacent and hypotenuse relative to that angle"
    >
      {/* The triangle is narrower than it looks like it should be, on purpose:
          "opposite" has to be written OUTSIDE the vertical side, and at the
          old width it ran off the edge of the box and rendered as "opposit". */}
      <Fig d="M 30 92 L 150 92 L 150 30 Z" />
      <RightAngle x={150} y={92} dx={-1} dy={-1} />
      <Angle d={wedge(30, 92, 26, 0, 27.3)} />
      <text x={60} y={86} className={label}>θ</text>
      <text x={90} y={107} textAnchor="middle" className={plainLabel}>adjacent</text>
      <text x={156} y={64} className={plainLabel}>opposite</text>
      <text x={82} y={52} textAnchor="middle" className={plainLabel}>hypotenuse</text>
    </Frame>
  );
}

function SineRule(props: DiagramProps) {
  return (
    <Frame
      caption={"side a is opposite angle A"}
      {...props}
      label="A triangle with no right angle, showing that each side is labelled with the lower-case letter of the angle opposite it"
    >
      <Fig d="M 30 90 L 190 90 L 132 26 Z" />
      <Angle d={wedge(30, 90, 22, 0, 32.2)} />
      <Angle d={wedge(190, 90, 22, 132.2, 180)} />
      <Angle d={wedge(132, 26, 18, 209.3, 312.2)} />
      <text x={54} y={84} className={label}>A</text>
      <text x={168} y={84} className={label}>B</text>
      <text x={127} y={52} className={label}>C</text>
      <text x={110} y={105} textAnchor="middle" className={plainLabel}>c</text>
      <text x={166} y={54} className={plainLabel}>a</text>
      <text x={72} y={54} className={plainLabel}>b</text>
    </Frame>
  );
}

function CosineRule(props: DiagramProps) {
  return (
    <Frame
      caption={"a² = b² + c² − 2bc cos A — a is opposite A"}
      {...props}
      label="A triangle with the angle A marked between the two known sides b and c, and side a opposite it"
    >
      <Fig d="M 30 90 L 190 90 L 132 26 Z" />
      <Angle d={wedge(30, 90, 24, 0, 32.2)} />
      <text x={56} y={84} className={label}>A</text>
      <text x={110} y={105} textAnchor="middle" className={plainLabel}>c</text>
      <text x={72} y={54} className={plainLabel}>b</text>
      <text x={166} y={54} className={label}>a</text>
    </Frame>
  );
}

// ─── Constructions and bearings ─────────────────────────────────────────────

function PerpendicularBisector(props: DiagramProps) {
  return (
    <Frame
      caption={"keep the arcs — they are the method mark"}
      {...props}
      label="A line segment with compass arcs drawn from each end, crossing above and below, and the perpendicular bisector drawn through the crossings"
    >
      <Fig d="M 55 58 L 165 58" />
      <Mark d={arc(55, 58, 72, -55, 55)} />
      <Mark d={arc(165, 58, 72, 125, 235)} />
      <Fig d="M 110 12 L 110 104" dashed />
      <RightAngle x={110} y={58} dx={1} dy={-1} />
      <circle cx={55} cy={58} r={2.6} className="fill-current opacity-60" />
      <circle cx={165} cy={58} r={2.6} className="fill-current opacity-60" />
    </Frame>
  );
}

function AngleBisector(props: DiagramProps) {
  return (
    <Frame
      caption={"the bisector cuts the angle into two equal halves"}
      {...props}
      label="An angle with compass arcs used to bisect it, and the bisector drawn from the vertex"
    >
      <Fig d={ray(45, 88, 150, 0)} />
      <Fig d={ray(45, 88, 150, 52)} />
      <Mark d={arc(45, 88, 46, -6, 58)} />
      <Mark d={arc(91, 88, 44, 0, 66)} />
      <Mark d={arc(73.3, 51.7, 44, -30, 30)} />
      <Fig d={ray(45, 88, 150, 26)} dashed />
      <Angle d={wedge(45, 88, 22, 0, 26)} />
      <Angle d={wedge(45, 88, 30, 26, 52)} />
    </Frame>
  );
}

function Bearing(props: DiagramProps) {
  return (
    <Frame
      caption={"from north, clockwise, always three figures"}
      {...props}
      label="A bearing measured clockwise from a north line at point A to point B, written with three figures"
    >
      <Fig d="M 78 96 L 78 18" dashed />
      <Mark d="M 73 25 L 78 15 L 83 25" />
      <text x={78} y={12} textAnchor="middle" className={plainLabel}>N</text>
      <Fig d="M 78 96 L 172 60" />
      <Angle d={wedge(78, 96, 34, 21, 90)} />
      <Mark d={arc(78, 96, 34, 90, 21)} />
      <circle cx={78} cy={96} r={3} className="fill-current opacity-70" />
      <circle cx={172} cy={60} r={3} className="fill-current opacity-70" />
      <text x={68} y={104} textAnchor="end" className={plainLabel}>A</text>
      <text x={180} y={58} className={plainLabel}>B</text>
      <text x={104} y={62} className={label}>069°</text>
    </Frame>
  );
}

// ─── Probability ────────────────────────────────────────────────────────────

function TreeDiagram(props: DiagramProps) {
  return (
    <Frame
      caption={"multiply along the branches, add down the ends"}
      {...props}
      label="A two-stage probability tree diagram, showing that probabilities multiply along a branch and each pair of branches adds to one"
    >
      <Fig d="M 26 58 L 84 30" />
      <Fig d="M 26 58 L 84 88" />
      <Fig d="M 88 28 L 150 14" />
      <Fig d="M 88 28 L 150 46" />
      <Fig d="M 88 90 L 150 72" />
      <Fig d="M 88 90 L 150 104" />
      <text x={48} y={36} className={plainLabel}>0.3</text>
      <text x={48} y={82} className={plainLabel}>0.7</text>
      <text x={112} y={14} className={plainLabel}>0.3</text>
      <text x={112} y={44} className={plainLabel}>0.7</text>
      <text x={112} y={74} className={plainLabel}>0.3</text>
      <text x={112} y={104} className={plainLabel}>0.7</text>
      <text x={156} y={17} className={label}>0.09</text>
    </Frame>
  );
}

function VennTwoSets(props: DiagramProps) {
  return (
    <Frame
      caption={"every outcome sits in exactly one region"}
      {...props}
      label="A Venn diagram of two overlapping sets inside a rectangle, with the overlap and the outside region labelled"
    >
      <Fig d="M 12 10 L 208 10 L 208 100 L 12 100 Z" />
      <circle cx={84} cy={55} r={33} className={line} strokeWidth={2} fill="none" />
      <circle cx={136} cy={55} r={33} className={line} strokeWidth={2} fill="none" />
      <text x={62} y={59} textAnchor="middle" className={plainLabel}>A only</text>
      <text x={158} y={59} textAnchor="middle" className={plainLabel}>B only</text>
      <text x={110} y={59} textAnchor="middle" className={label}>both</text>
      <text x={30} y={92} className={plainLabel}>neither</text>
    </Frame>
  );
}

// ════════════════════════════════════════════════════════════════════════════
// The registry. Content names a diagram; this is where the name becomes a
// picture. Adding one means adding it here and nowhere else.
// ════════════════════════════════════════════════════════════════════════════
export const MATHS_DIAGRAMS = {
  // Angles and 2D shapes
  "angles-on-a-line": AnglesOnALine,
  "angles-around-a-point": AnglesAroundAPoint,
  "vertically-opposite": VerticallyOpposite,
  "angles-in-a-triangle": AnglesInATriangle,
  "parallel-corresponding": ParallelCorresponding,
  "parallel-alternate": ParallelAlternate,
  "parallel-co-interior": ParallelCoInterior,
  "exterior-angle-triangle": ExteriorAngleTriangle,
  "polygon-exterior-angles": PolygonExteriorAngles,
  "triangle-perpendicular-height": TrianglePerpendicularHeight,
  "trapezium-area": TrapeziumArea,

  // Circle theorems
  "circle-parts": CircleParts,
  "circle-angle-at-centre": CircleAngleAtCentre,
  "circle-semicircle": CircleSemicircle,
  "circle-same-segment": CircleSameSegment,
  "circle-cyclic-quadrilateral": CircleCyclicQuadrilateral,
  "circle-tangent-radius": CircleTangentRadius,
  "circle-alternate-segment": CircleAlternateSegment,
  "circle-sector-arc": CircleSectorArc,

  // Pythagoras and trigonometry
  "pythagoras": Pythagoras,
  "sohcahtoa": Sohcahtoa,
  "sine-rule": SineRule,
  "cosine-rule": CosineRule,

  // Constructions and bearings
  "perpendicular-bisector": PerpendicularBisector,
  "angle-bisector": AngleBisector,
  "bearing": Bearing,

  // Probability
  "tree-diagram": TreeDiagram,
  "venn-two-sets": VennTwoSets,
} as const;

export type DiagramName = keyof typeof MATHS_DIAGRAMS;

/**
 * Draws the diagrams a key-fact block asked for.
 *
 * An unknown name is skipped rather than crashing the page — but
 * check-content.mjs fails the build first, so it should never get here.
 */
export function DiagramRow({ names }: { names: readonly string[] }) {
  const found = names.filter((name): name is DiagramName => name in MATHS_DIAGRAMS);
  if (found.length === 0) return null;

  return (
    <div
      className={`mt-5 grid gap-4 ${found.length > 1 ? "sm:grid-cols-2" : "max-w-sm"}`}
    >
      {found.map((name) => {
        const Diagram = MATHS_DIAGRAMS[name];
        return (
          <div
            key={name}
            className="rounded-xl border border-black/10 bg-white/70 p-3 dark:border-white/10 dark:bg-white/5"
          >
            <Diagram />
          </div>
        );
      })}
    </div>
  );
}
