#!/usr/bin/env python3
"""Render a mascot from Mascots.tsx to a PNG so you can actually LOOK at it.

    python3 scripts/preview-mascot.py Sterling out.png [background]

WHY THIS EXISTS
---------------
The mascots are hand-written SVG: a hundred coordinates typed by hand. Numbers
that look sensible in the file produce a hand growing out of a briefcase, and
there is no way to know without seeing it. Every round of mascot feedback so far
("the legs look like two circles", "get rid of the equator") has been Matthew
looking at something that was never looked at before it shipped.

WHY IT IS NOT JUST `convert file.svg file.png`
----------------------------------------------
ImageMagick's built-in SVG renderer IGNORES the `opacity` attribute — and
opacity is doing most of the work in these drawings, because every form is
shaded with a black overlay at 5-20%. Rendered by ImageMagick alone, every one
of those overlays comes out SOLID BLACK, so half the character looks like a
silhouette and you "fix" problems that were never there. That happened; this
script exists because of it.

So each element is rendered on its own, and the layers are composited here with
their real alpha. Slower, and correct.

(The proper fix is a real SVG renderer — rsvg-convert or resvg. Neither could be
installed in this sandbox, hence the workaround.)
"""

import re
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image

SOURCE = Path(__file__).resolve().parent.parent / "app" / "components" / "Mascots.tsx"
SCALE = 3  # pixels per SVG unit


def extract(component: str) -> str:
    src = SOURCE.read_text(encoding="utf8")
    start = src.index(f"export function {component}(")
    body = src[start:]
    return body[body.index("<svg") : body.index("</svg>") + 6]


def to_plain_svg(jsx: str) -> str:
    """Turn the JSX dialect into SVG a renderer will accept."""
    out = re.sub(r"\{/\*.*?\*/\}", "", jsx, flags=re.S)        # JSX comments
    out = re.sub(r"\{(-?[\d.]+)\}", r'"\1"', out)              # strokeWidth={2.6}
    out = re.sub(r"\s*\{\.\.\.props\}", "", out)
    # Quill's ruff is generated by a JSX .map(), which is code rather than
    # markup. Strip the React-only bits so the shapes inside still render;
    # anything left unparseable is skipped in main() rather than crashing.
    out = re.sub(r'\s*key=\{[^}]*\}', "", out)
    out = re.sub(r'cy=\{[^}]*\}', 'cy="70"', out)
    out = re.sub(r'\{\[[^\]]*\]\.map\([^)]*\) => \(', "", out)
    out = re.sub(r'cx=\{cx\}', 'cx="60"', out)
    out = re.sub(r'\)\)\}', "", out)
    out = re.sub(r'\s*(role|aria-label|className)="[^"]*"', "", out)
    for camel, dashed in (
        ("strokeWidth", "stroke-width"),
        ("strokeLinecap", "stroke-linecap"),
        ("strokeLinejoin", "stroke-linejoin"),
        ("strokeDasharray", "stroke-dasharray"),
        ("clipPath", "clip-path"),
        ("shapeRendering", "shape-rendering"),
        ("fillOpacity", "fill-opacity"),
    ):
        out = out.replace(camel, dashed)
    return out


def viewbox(svg: str) -> tuple[str, int, int]:
    vb = re.search(r'viewBox="([\d.\s-]+)"', svg).group(1)
    _, _, w, h = (float(n) for n in vb.split())
    return vb, int(w * SCALE), int(h * SCALE)


def elements(svg: str) -> list[tuple[str, float]]:
    """Every self-closing shape, paired with the opacity to composite it at."""
    inner = svg[svg.index(">") + 1 : svg.rindex("</svg>")]
    found = []
    for tag in re.findall(r"<(?:path|rect|circle|ellipse|polygon|line|g)\b[^>]*?/>", inner):
        m = re.search(r'\sopacity="([\d.]+)"', tag)
        alpha = float(m.group(1)) if m else 1.0
        found.append((re.sub(r'\sopacity="[\d.]+"', "", tag), alpha))
    return found


def render(tag: str, vb: str, w: int, h: int, tmp: Path) -> Image.Image:
    one = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}" width="{w}" height="{h}">{tag}</svg>'
    svg_path, png_path = tmp / "one.svg", tmp / "one.png"
    svg_path.write_text(one, encoding="utf8")
    subprocess.run(
        ["convert", "-background", "none", str(svg_path), str(png_path)],
        check=True,
        capture_output=True,
    )
    return Image.open(png_path).convert("RGBA")


def main() -> None:
    if len(sys.argv) < 3:
        sys.exit(__doc__)

    component, out_path = sys.argv[1], sys.argv[2]
    background = sys.argv[3] if len(sys.argv) > 3 else "#0d9488"

    svg = to_plain_svg(extract(component))
    vb, w, h = viewbox(svg)

    canvas = Image.new("RGBA", (w, h), background)
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        skipped = 0
        for tag, alpha in elements(svg):
            try:
                layer = render(tag, vb, w, h, tmp)
            except subprocess.CalledProcessError:
                # One unrenderable element should not cost you the whole
                # preview — seeing 59 of 60 layers still tells you what you
                # needed to know.
                skipped += 1
                continue
            if alpha < 1.0:
                # Scale the layer's own alpha channel, which is what the
                # renderer refused to do.
                r, g, b, a = layer.split()
                layer = Image.merge("RGBA", (r, g, b, a.point(lambda v: int(v * alpha))))
            canvas = Image.alpha_composite(canvas, layer)

    canvas.convert("RGB").save(out_path)
    note = f", {skipped} skipped" if skipped else ""
    print(f"{component}: {len(elements(svg))} layers{note} → {out_path} ({w}x{h})")


if __name__ == "__main__":
    main()
